apiVersion: apps/v1
kind: Deployment
metadata:
  name: pavan-deployment
  namespace: dev


spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd


template::
 metadata: 
  labels:
    app:httpd
spec:
containers:
 - name: httpd
   image: httpd:latest
   
