apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: dev
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: nginx:latest
      ports:
        - containerPort: 80